name: PHP-CS-Fixer Review

on:
  pull_request:

jobs:
  php-cs-fixer-review:
    name: Check PHP Code with PHP-CS-Fixer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: php-cs-fixer, cs2pr

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: PHP CS Fixer with Reviewdog
        run: |
          php-cs-fixer fix --dry-run --using-cache=no --format=checkstyle | cs2pr
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
